In [1]:
import numpy as np

In [4]:
from __future__ import division
5/2

2.5

In [3]:
5.0/2

2.5

In [5]:
arr1 = np.array([[1,2,3,4],[64,81,100,121]])

In [6]:
arr1*arr1

array([[    1,     4,     9,    16],
       [ 4096,  6561, 10000, 14641]])

In [7]:
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [8]:
1/arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.015625  ,  0.01234568,  0.01      ,  0.00826446]])

In [9]:
arr1 ** 3

array([[      1,       8,      27,      64],
       [ 262144,  531441, 1000000, 1771561]])