In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([-0.74158674,  0.12490333, -0.18596089, -0.82023006,  0.59001542,
       -0.63685925,  0.2519211 ,  2.01774017, -0.82668959, -1.09160268])

In [7]:
B = np.random.randn(10)
B

array([ 0.19356052,  0.61847707,  0.26663233, -0.54482604, -0.88343632,
       -0.15197452, -0.38181447, -1.19275699,  0.09520567,  0.73934305])

In [8]:
# Binary Function
np.add(A,B)

array([-0.54802622,  0.74338041,  0.08067144, -1.36505609, -0.29342091,
       -0.78883377, -0.12989337,  0.82498318, -0.73148392, -0.35225963])

In [9]:
np.maximum(A,B)

array([ 0.19356052,  0.61847707,  0.26663233, -0.54482604,  0.59001542,
       -0.15197452,  0.2519211 ,  2.01774017,  0.09520567,  0.73934305])

In [11]:
website = 'htttp://www.bing.com'
import webbrowser 
webbrowser.open(website)

True