In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 = Series([0,1,2],index=['T','U','V'])

In [8]:
ser2 = Series([3,4],index=['X','Y'])

In [9]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2],axis=1)

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [11]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [12]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])

In [13]:
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','Z'])

In [14]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  0.069125  0.520540 -0.648218
1       NaN -1.546388  0.336556 -1.285755
2       NaN -0.698298  0.462543 -1.227694
3       NaN  1.182890 -1.307728  0.584684
0  0.151791       NaN -0.401230 -1.116340
1  0.294409       NaN -0.728667 -1.762312
2 -1.073122       NaN  1.006168  0.014413

In [15]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN  0.069125  0.520540 -0.648218
1       NaN -1.546388  0.336556 -1.285755
2       NaN -0.698298  0.462543 -1.227694
3       NaN  1.182890 -1.307728  0.584684
4  0.151791       NaN -0.401230 -1.116340
5  0.294409       NaN -0.728667 -1.762312
6 -1.073122       NaN  1.006168  0.014413